exclude:
- start.bat

timezone: Europe/Berlin
title: WurstClient.net
url: "https://www.wurstclient.net"

plugins:
  - jekyll-sitemap
  - jekyll-feed

author: Alexander01998

feed:
  posts_limit: 20
  collections:
    updates:
      path: "/wurst-updates.xml"

mcversions:
  "snapshots": "Snapshots"
  "1.16.5": "1.16.5"
  "1.16.4": "1.16.4"
  "1.16.3": "1.16.3"
  "1.16.2": "1.16.2"
  "1.16.1": "1.16.1"
  "1.16": "1.16"
  "1.15.2": "1.15.2"
  "1.15.1": "1.15.1"
  "1.15": "1.15"
  "1.14.4": "1.14.4"
  "1.14.3": "1.14.3"
  "1.14.2": "1.14.2"
  "1.14_combat-3": "1.14 Combat Test 3"
  "1.12": "1.12 - 1.12.2"
  "1.12 OF": "1.12 - 1.12.2 + OptiFine"
  "1.11": "1.11 - 1.11.2"
  "1.11 OF": "1.11 - 1.11.2 + OptiFine"
  "1.10": "1.10 - 1.10.2"
  "1.9": "1.9 - 1.9.2"
  "1.8": "1.8 - 1.8.9"
  "1.8 OF": "1.8 - 1.8.9 + OptiFine"
  "1.7": "1.7.2 - 1.7.10"

collections:
  updates:
    output: true
    permalink: /updates/:slug/
  wiki:
    output: true
    permalink: /wiki/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  tutorials_de:
    output: true
    permalink: /de/tutorials/:path/
  redirects:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author: Alexander01998
  - scope:
      path: ""
      type: updates
    values:
      layout: update
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
      secondarytitle: Wurst Wiki
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
  - scope:
      path: ""
      type: redirects
    values:
      layout: redirect
